BUILTIN_APPS = (
    "3DBuilder",
    "Appconnector",
    "BingFinance",
    "BingNews",
    "BingSports",
    "BingTranslator",
    "BingWeather",
    "CandyCrush",
    "CommsPhone",
    "Facebook",
    "HiddenCityMysteryOfShadows",
    "MarchOfEmpires",
    "Messaging",
    "Microsoft3DViewer",
    "MicrosoftOfficeHub",
    "MicrosoftPowerBIForWindows",
    "MicrosoftSolitaireCollection",
    "MicrosoftStickyNotes",
    "Minecraft",
    "Netflix",
    "NetworkSpeedTest",
    "OfficeLens",
    "OneConnect",
    "OneNote",
    "People",
    "Photos",
    "Print3D",
    "SkypeApp",
    "Twitter",
    "Wallet",
    "Whiteboard",
    "WindowsAlarms",
    "WindowsCalculator",
    "WindowsCamera",
    "WindowsMaps",
    "WindowsPhone",
    "WindowsSoundRecorder",
    "Xbox",
    "YourPhone",
    "ZuneMusic",
    "ZuneVideo",
    "windowscommunicationsapps",
)

TRACKING_AND_TELEMETRY = {
    "advertising_id": "Идентификатор рекламы",
    "browser_access_to_local_language": "Доступ веб-сайтов к списку установленных языков в системе",
    "connected_user_experiences_and_telemetry": "Сбор диагностических данных и телеметрия",
    "customer_experience_improvement_program": "Программа улучшения качества ПО (Customer Experience Improvement зrogram)",
    "microsoft_help_feedback": "Программа улучшения справки (Help Experience Improvement program)",
    "windows_feedback": "Не показывать уведомления об отзывах",
}


CONFIG_SECTIONS = {
    "DELETE_BUILTIN_APPS": BUILTIN_APPS,
    "DIAGNOSTIC_TRACKING_AND_TELEMETRY": tuple(TRACKING_AND_TELEMETRY.keys()),
    "INTERNET_EXPLORER": None,
    "LOCATION_AND_SENSORS": None,
    "MICROPHONE": None,
    "ONEDRIVE": None,
    "POWERSHELL_SCRIPTS_EXECUTION": None,
    "REMOTE_ACCESS": None,
    "WEBCAM": None,
}
