BUILTIN_APPS = {
    "3DBuilder":"3D Builder",
    "Appconnector":"App Connector",
    "BingFinance":"Bing finance",
    "BingNews":"Bing News",
    "BingSports":"Bing Sports",
    "BingTranslator":"Bing Translator",
    "BingWeather":"Bing Weather",
    "CandyCrush":"Candy Crush All Games",
    "CommsPhone":"Phone",
    "Facebook":"Facebook",
    "HiddenCityMysteryOfShadows":"Hidden city mystery of shadows",
    "MarchOfEmpires":"Марш Империй",
    "Messaging":"Сообщения (Майкрософт)",
    "Microsoft3DViewer":"Средство просмотра смешанной реальности",
    "MicrosoftOfficeHub":"My Office",
    "MicrosoftPowerBIForWindows":"microsoftpowerbiforwindows",
    "MicrosoftSolitaireCollection":"Microsoft Solitaire Collection",
    "MicrosoftStickyNotes":"Корпорация Майкрософт записки",
    "Minecraft":"Minecraft",
    "Netflix":"Netflix",
    "NetworkSpeedTest":"Проверка скорости сети",
    "OfficeLens":"officelens",
    "OneConnect":"Платные данные Wi-Fi и сотовой сети",
    "OneNote":"OneNote",
    "People":"Люди (Майкрософт)",
    "Photos":"Фотографии (Майкрософт)",
    "Print3D":"Print 3D",
    "SkypeApp":"Skype",
    "Twitter":"Twitter",
    "Wallet":"Microsoft Pay",
    "Whiteboard":"Microsoft Whiteboard",
    "WindowsAlarms":"Windows будильники и часы",
    "WindowsCalculator":"Калькулятор Windows",
    "WindowsCamera":"Камеры в Windows",
    "WindowsMaps":"Карты Windows",
    "WindowsPhone":"windowsphone",
    "WindowsSoundRecorder":"Запись голоса Windows",
    "Xbox":"Xbox",
    "YourPhone":"Ваш телефон",
    "ZuneMusic":"Музыка Groove",
    "ZuneVideo":"Кино и ТВ",
    "windowscommunicationsapps":"Почта и календарь",
}
BUILTIN_APPS = {key.lower(): value for key,value in BUILTIN_APPS.items() }
TRACKING_AND_TELEMETRY = {
    "advertising_id": "Идентификатор рекламы",
    "browser_access_to_local_language": "Доступ веб-сайтов к списку установленных языков в системе",
    "connected_user_experiences_and_telemetry": "Сбор диагностических данных и телеметрия",
    "customer_experience_improvement_program": "Программа улучшения качества ПО (Customer Experience Improvement зrogram)",
    "microsoft_help_feedback": "Программа улучшения справки (Help Experience Improvement program)",
    "windows_feedback": "Не показывать уведомления об отзывах",
}


CONFIG_SECTIONS = {
    "DELETE_BUILTIN_APPS": BUILTIN_APPS,
    "DIAGNOSTIC_TRACKING_AND_TELEMETRY": tuple(TRACKING_AND_TELEMETRY.keys()),
    "INTERNET_EXPLORER": None,
    "LOCATION_AND_SENSORS": None,
    "MICROPHONE": None,
    "ONEDRIVE": None,
    "POWERSHELL_SCRIPTS_EXECUTION": None,
    "REMOTE_ACCESS": None,
    "WEBCAM": None,
}
